### ISSUE TITLE
Suppot Kbps bandwidth network setting

### ISSUE THREAD

**Issue by rware** [cmu-snap/themis-backend#17]
Currently BESS expects the bandwidth to be atleast 1 Mbps.

This can be changed by changing two lines:

1. Change ```int``` to ```float``` in cctestbed python file: https://github.com/rware/cctestbed/blob/cloudlab/cctestbedv2.py#L622
2. Change ```int``` to ```float``` in BESS pipeline file: https://github.com/rware/cctestbed/blob/cloudlab/active-middlebox-pmd.bess#L11

The unit for btlbw will still be Mbps, but then you'll be able to specify a float so you can get Kbps.

**Comment by arukshani** [comment]
Fixed and changes are in https://github.com/rware/cctestbed/commit/435c830599e3044c8d77690955b6a8a926e8715d
