### ISSUE TITLE
Ensure correct screen resolution sent to Youtube

### ISSUE THREAD

**Issue by rware** [cmu-snap/themis-backend#4]
Youtube may change the size of the video files it sends, based on the screen resolution sent by the browser. Themis needs to ensure that a good screen resolution is sent to Youtube so that this does not impact the results.

**Comment by arukshani** [comment]
'--resolution' flag has been introduced to set the window sizes (width and height). 

A separate script is there to run video experiments called 'ccalg_predict_video.py'. Implementation can be found here >> https://github.com/rware/cctestbed/blob/ruk/ccalg_predict_video.py  

E.g. python3.6 ccalg_predict_video.py --website www.youtube.com "https://www.youtube.com/embed/aqz-KE-bpKQ?autoplay=1" --network 5 35 --resolution 1920 1080
