### ISSUE TITLE
Add ability to run local video experiments with cctestbed

### ISSUE THREAD

**Issue by rware** [cmu-snap/themis-backend#5]
Currently, the testbed supports running local experiments with iperf3, where you can specify the congestion control algorithm and run a bulk download for some amount of time (see cctestbedv2.py). We would like to support this functionality for video.

The goal of this new feature is to be able to run a local experiment serving a video over a specified congestion control algorithm. (Maybe we could generate training samples for video!) Currently, the testbed supports running this functionality for fairness experiments only (see ccalg_fairness.py). 

In the fairness experiments, this worked by starting an apache server and serving a standard BigBuckBunny video using this standard DASH dataset (https://dash.itec.aau.at/dash-dataset/) . In Cloudlab, these files could be found under /mnt/video on cctestbed-client machine.

To support running video experiments, outside of fairness experiments, we first want to support the ability to run a local video experiment in cctestbedv2.py.

This will require a few changes:

1. The testbed setup in Cloudlab does not copy the required index.html and dash.min.js file to correct folder so that the apache server can serve them. You'll need to manually copy these files in www/ to /var/www/html. Later we can update setup_cloudlab.py to move  these to the right place. 
2. Make specifying if flows should be an iperf or video flow an option in cctestbedv2.py configuration files. cctestbedv2.py takes a config file as input (You can generate a config file using cctesbed_generate_experiments.py). You specify flows in this file like this:
```
        flows:
        - ccalg: cubic
          start_time: 0
          end_time: 10
          rtt: 40
```
Add the ability to specify the kind of flow with the options "video" or "iperf" like this:
```
        flows:
        - ccalg: cubic
          start_time: 0
          end_time: 10
          rtt: 40
          kind: video
```
In order to do this, you'll need to update the load_config_file function in cctestbedv2.py which currently forces all flows to be "iperf" flows. 
3. Add ability to run video streaming in cctestbedv2.py. Currently, the _run_all_flows function in cctestbedv2.py assumes you are only going to run iperf flows. Now, you should assume the flow could be an iperf flow or a video flow, and you can determine which one by checking the "kind" variable in the Flow object. When you want to run a video stream, you'll need to do the following (You can see examples of how to do most of these things in ccalg_fairness.py's run_video function):
- Start the apache server on cctestbed-client.
- Change the default congestion control algorithm on the cctesbed-client to the flow's desired CCA: http://sgros.blogspot.com/2012/12/controlling-which-congestion-control.html
- Run google-chrome to stream the video. 
- Stop google-chrome & the apache server when the experiment is done.

To verify this all works, you should try to run an experiment and see if you can get a queue occupancy graph in the end. See if you change the CCA if you see any noticable difference in the queue occupancy graph (it's possible you won't). You may also find it helpful to write unittests, you can put test files in the tests/ folder (we've been using the pytest framework: https://docs.pytest.org/en/latest/).

Some issues to consider:
- You cannot specify a CCA per-flow with video (you have to set a default CCA for the entire machine), so if you're running a video experiment, you may want to enforce that there be only one flow. For now, this works for our use-case, but in the future we may want to run multiple video flows for some reason?

**Comment by arukshani** [comment]
Implementation can be found in here > https://github.com/rware/cctestbed/tree/ruk

**Comment by rware** [comment]
Is it possible for you to merge the changes you made into the themis-backend repo?

**Comment by arukshani** [comment]
Done. I have merged it to master branch of themis-backend repo.
